### ISSUE TITLE
DS3231M  power to VBAT

### ISSUE THREAD

**Issue by bobricius** [RafaelRiber/RetroWatch#1]
Hi, connect power for DS3231 to VBAT instead VCC (VCC>GND) it reduce standby power consumption from 200uA to 2uA, but if you have not using any standby modes in firmware it is useless. ;)

**Comment by RafaelRiber** [comment]
Thanks for the tip ! I'll implement this in V2.

**Comment by RafaelRiber** [comment]
Just a little question: should I power it only by VBAT, or use VCC when the Microcontroller is on, and VBAT when only the DS3231 is on ?

**Comment by bobricius** [comment]
connect vcc to gnd and you can power DS3231 via vbat. I have using this in my watches, I have detection on startup with IIC scan if is DS3231 connected if not I start Timer2 in async mode .... there is complete MCU consumtion 0.9uA !!! so I decided to remove all charging related circuits. I read comments in sprakfun bigtime firmware that with this consumption you can display time every hour for 3years ... but of course I am not test it. Some tips about charging, load sharing, ds3231 ... http://blog.zakkemble.co.uk/diy-digital-wristwatch/ and about low power design you can read here https://github.com/sparkfun/BigTime/blob/master/Firmware/BigTime/BigTime.ino

**Comment by RafaelRiber** [comment]
Ok I see. Thanks ! I'll do that in V2. I decided to stick with using a switch to cut power to the MCU instead of ultra-low power sleep, becuase I wanted to keep it as simple as possible. I will definetely look into it for future projects though ! Also, thanks for the links !
