### ISSUE TITLE
Battery and watch strap not included in BOM.

### ISSUE THREAD

**Issue by nullcopy** [RafaelRiber/RetroWatch#2]
What battery and strap were used?

**Comment by RafaelRiber** [comment]
I used a 500mAh Lithium Ion Polymer battery from Adafruit, that fits perfectly under the board: **https://www.adafruit.com/products/1578**
and an old strap from a random watch I had.
Any **_20mm width_** strap that's only in **one piece**, like **[this one](https://www.amazon.com/ArtStyle-Thickness-Quality-Brushed-Buckle/dp/B01AWP0U52/ref=sr_1_2?ie=UTF8&qid=1467053548&sr=8-2&keywords=nato+watch+strap)** should do.
Be sure to select _20mm_ in the size selection though !
